name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "index.html"
      - "style.css"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4

      - name: Fetch and checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      - name: Copy files from master to gh-pages
        run: |
          git checkout master -- index.html style.css

      - name: Commit and push changes to gh-pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add index.html style.css
          git diff --quiet && git diff --staged --quiet || git commit -m "Update deployed files from master"
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
